rec.o: rec.cc reccl.h ../ddconfig.h ../custom.h ../pobjcl.h ../ddconfig.h \
  ../pobjt.h ../eventcl.h
gui.o: gui.cc guicl.h ../ddconfig.h ../custom.h ../pobjcl.h ../ddconfig.h \
  ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
  ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h guicl.h \
  ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ifcl.h ../sim.src/guiobjcl.h
if.o: if.cc ifcl.h ../ddconfig.h ../custom.h ../pobjcl.h ../ddconfig.h \
  ../pobjt.h ../eventcl.h ../sim.src/guiobjcl.h
